// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCollectionsParams creates a new GetCollectionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollectionsParams() *GetCollectionsParams {
	return &GetCollectionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCollectionsParamsWithTimeout creates a new GetCollectionsParams object
// with the ability to set a timeout on a request.
func NewGetCollectionsParamsWithTimeout(timeout time.Duration) *GetCollectionsParams {
	return &GetCollectionsParams{
		timeout: timeout,
	}
}

// NewGetCollectionsParamsWithContext creates a new GetCollectionsParams object
// with the ability to set a context for a request.
func NewGetCollectionsParamsWithContext(ctx context.Context) *GetCollectionsParams {
	return &GetCollectionsParams{
		Context: ctx,
	}
}

// NewGetCollectionsParamsWithHTTPClient creates a new GetCollectionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollectionsParamsWithHTTPClient(client *http.Client) *GetCollectionsParams {
	return &GetCollectionsParams{
		HTTPClient: client,
	}
}

/*
GetCollectionsParams contains all the parameters to send to the API endpoint

	for the get collections operation.

	Typically these are written to a http.Request.
*/
type GetCollectionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get collections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionsParams) WithDefaults() *GetCollectionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get collections params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get collections params
func (o *GetCollectionsParams) WithTimeout(timeout time.Duration) *GetCollectionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get collections params
func (o *GetCollectionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get collections params
func (o *GetCollectionsParams) WithContext(ctx context.Context) *GetCollectionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get collections params
func (o *GetCollectionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get collections params
func (o *GetCollectionsParams) WithHTTPClient(client *http.Client) *GetCollectionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get collections params
func (o *GetCollectionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetCollectionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
