// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dccn-tg/dr-gateway/pkg/swagger/client/models"
)

// GetCollectionsOuIDReader is a Reader for the GetCollectionsOuID structure.
type GetCollectionsOuIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCollectionsOuIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCollectionsOuIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetCollectionsOuIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCollectionsOuIDOK creates a GetCollectionsOuIDOK with default headers values
func NewGetCollectionsOuIDOK() *GetCollectionsOuIDOK {
	return &GetCollectionsOuIDOK{}
}

/*
GetCollectionsOuIDOK describes a response with status code 200, with default header values.

success
*/
type GetCollectionsOuIDOK struct {
	Payload *models.ResponseBodyCollections
}

// IsSuccess returns true when this get collections ou Id o k response has a 2xx status code
func (o *GetCollectionsOuIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get collections ou Id o k response has a 3xx status code
func (o *GetCollectionsOuIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get collections ou Id o k response has a 4xx status code
func (o *GetCollectionsOuIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get collections ou Id o k response has a 5xx status code
func (o *GetCollectionsOuIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get collections ou Id o k response a status code equal to that given
func (o *GetCollectionsOuIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get collections ou Id o k response
func (o *GetCollectionsOuIDOK) Code() int {
	return 200
}

func (o *GetCollectionsOuIDOK) Error() string {
	return fmt.Sprintf("[GET /collections/ou/{id}][%d] getCollectionsOuIdOK  %+v", 200, o.Payload)
}

func (o *GetCollectionsOuIDOK) String() string {
	return fmt.Sprintf("[GET /collections/ou/{id}][%d] getCollectionsOuIdOK  %+v", 200, o.Payload)
}

func (o *GetCollectionsOuIDOK) GetPayload() *models.ResponseBodyCollections {
	return o.Payload
}

func (o *GetCollectionsOuIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyCollections)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCollectionsOuIDInternalServerError creates a GetCollectionsOuIDInternalServerError with default headers values
func NewGetCollectionsOuIDInternalServerError() *GetCollectionsOuIDInternalServerError {
	return &GetCollectionsOuIDInternalServerError{}
}

/*
GetCollectionsOuIDInternalServerError describes a response with status code 500, with default header values.

failure
*/
type GetCollectionsOuIDInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this get collections ou Id internal server error response has a 2xx status code
func (o *GetCollectionsOuIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get collections ou Id internal server error response has a 3xx status code
func (o *GetCollectionsOuIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get collections ou Id internal server error response has a 4xx status code
func (o *GetCollectionsOuIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get collections ou Id internal server error response has a 5xx status code
func (o *GetCollectionsOuIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get collections ou Id internal server error response a status code equal to that given
func (o *GetCollectionsOuIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get collections ou Id internal server error response
func (o *GetCollectionsOuIDInternalServerError) Code() int {
	return 500
}

func (o *GetCollectionsOuIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /collections/ou/{id}][%d] getCollectionsOuIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCollectionsOuIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /collections/ou/{id}][%d] getCollectionsOuIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCollectionsOuIDInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetCollectionsOuIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
