// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetCollectionsProjectIDParams creates a new GetCollectionsProjectIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCollectionsProjectIDParams() *GetCollectionsProjectIDParams {
	return &GetCollectionsProjectIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCollectionsProjectIDParamsWithTimeout creates a new GetCollectionsProjectIDParams object
// with the ability to set a timeout on a request.
func NewGetCollectionsProjectIDParamsWithTimeout(timeout time.Duration) *GetCollectionsProjectIDParams {
	return &GetCollectionsProjectIDParams{
		timeout: timeout,
	}
}

// NewGetCollectionsProjectIDParamsWithContext creates a new GetCollectionsProjectIDParams object
// with the ability to set a context for a request.
func NewGetCollectionsProjectIDParamsWithContext(ctx context.Context) *GetCollectionsProjectIDParams {
	return &GetCollectionsProjectIDParams{
		Context: ctx,
	}
}

// NewGetCollectionsProjectIDParamsWithHTTPClient creates a new GetCollectionsProjectIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCollectionsProjectIDParamsWithHTTPClient(client *http.Client) *GetCollectionsProjectIDParams {
	return &GetCollectionsProjectIDParams{
		HTTPClient: client,
	}
}

/*
GetCollectionsProjectIDParams contains all the parameters to send to the API endpoint

	for the get collections project ID operation.

	Typically these are written to a http.Request.
*/
type GetCollectionsProjectIDParams struct {

	/* ID.

	   project identifier
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get collections project ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionsProjectIDParams) WithDefaults() *GetCollectionsProjectIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get collections project ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCollectionsProjectIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get collections project ID params
func (o *GetCollectionsProjectIDParams) WithTimeout(timeout time.Duration) *GetCollectionsProjectIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get collections project ID params
func (o *GetCollectionsProjectIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get collections project ID params
func (o *GetCollectionsProjectIDParams) WithContext(ctx context.Context) *GetCollectionsProjectIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get collections project ID params
func (o *GetCollectionsProjectIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get collections project ID params
func (o *GetCollectionsProjectIDParams) WithHTTPClient(client *http.Client) *GetCollectionsProjectIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get collections project ID params
func (o *GetCollectionsProjectIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get collections project ID params
func (o *GetCollectionsProjectIDParams) WithID(id string) *GetCollectionsProjectIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get collections project ID params
func (o *GetCollectionsProjectIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetCollectionsProjectIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
