// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Donders-Institute/dr-gateway/pkg/swagger/client/models"
)

// GetUsersOuIDReader is a Reader for the GetUsersOuID structure.
type GetUsersOuIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsersOuIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUsersOuIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetUsersOuIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUsersOuIDOK creates a GetUsersOuIDOK with default headers values
func NewGetUsersOuIDOK() *GetUsersOuIDOK {
	return &GetUsersOuIDOK{}
}

/*
GetUsersOuIDOK describes a response with status code 200, with default header values.

success
*/
type GetUsersOuIDOK struct {
	Payload *models.ResponseBodyUsers
}

// IsSuccess returns true when this get users ou Id o k response has a 2xx status code
func (o *GetUsersOuIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get users ou Id o k response has a 3xx status code
func (o *GetUsersOuIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get users ou Id o k response has a 4xx status code
func (o *GetUsersOuIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get users ou Id o k response has a 5xx status code
func (o *GetUsersOuIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get users ou Id o k response a status code equal to that given
func (o *GetUsersOuIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get users ou Id o k response
func (o *GetUsersOuIDOK) Code() int {
	return 200
}

func (o *GetUsersOuIDOK) Error() string {
	return fmt.Sprintf("[GET /users/ou/{id}][%d] getUsersOuIdOK  %+v", 200, o.Payload)
}

func (o *GetUsersOuIDOK) String() string {
	return fmt.Sprintf("[GET /users/ou/{id}][%d] getUsersOuIdOK  %+v", 200, o.Payload)
}

func (o *GetUsersOuIDOK) GetPayload() *models.ResponseBodyUsers {
	return o.Payload
}

func (o *GetUsersOuIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyUsers)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsersOuIDInternalServerError creates a GetUsersOuIDInternalServerError with default headers values
func NewGetUsersOuIDInternalServerError() *GetUsersOuIDInternalServerError {
	return &GetUsersOuIDInternalServerError{}
}

/*
GetUsersOuIDInternalServerError describes a response with status code 500, with default header values.

failure
*/
type GetUsersOuIDInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this get users ou Id internal server error response has a 2xx status code
func (o *GetUsersOuIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get users ou Id internal server error response has a 3xx status code
func (o *GetUsersOuIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get users ou Id internal server error response has a 4xx status code
func (o *GetUsersOuIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get users ou Id internal server error response has a 5xx status code
func (o *GetUsersOuIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get users ou Id internal server error response a status code equal to that given
func (o *GetUsersOuIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get users ou Id internal server error response
func (o *GetUsersOuIDInternalServerError) Code() int {
	return 500
}

func (o *GetUsersOuIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /users/ou/{id}][%d] getUsersOuIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetUsersOuIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /users/ou/{id}][%d] getUsersOuIdInternalServerError  %+v", 500, o.Payload)
}

func (o *GetUsersOuIDInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetUsersOuIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
