// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUsersOuIDParams creates a new GetUsersOuIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUsersOuIDParams() *GetUsersOuIDParams {
	return &GetUsersOuIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersOuIDParamsWithTimeout creates a new GetUsersOuIDParams object
// with the ability to set a timeout on a request.
func NewGetUsersOuIDParamsWithTimeout(timeout time.Duration) *GetUsersOuIDParams {
	return &GetUsersOuIDParams{
		timeout: timeout,
	}
}

// NewGetUsersOuIDParamsWithContext creates a new GetUsersOuIDParams object
// with the ability to set a context for a request.
func NewGetUsersOuIDParamsWithContext(ctx context.Context) *GetUsersOuIDParams {
	return &GetUsersOuIDParams{
		Context: ctx,
	}
}

// NewGetUsersOuIDParamsWithHTTPClient creates a new GetUsersOuIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUsersOuIDParamsWithHTTPClient(client *http.Client) *GetUsersOuIDParams {
	return &GetUsersOuIDParams{
		HTTPClient: client,
	}
}

/*
GetUsersOuIDParams contains all the parameters to send to the API endpoint

	for the get users ou ID operation.

	Typically these are written to a http.Request.
*/
type GetUsersOuIDParams struct {

	/* ID.

	   short name of the organisational unit
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get users ou ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersOuIDParams) WithDefaults() *GetUsersOuIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get users ou ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUsersOuIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get users ou ID params
func (o *GetUsersOuIDParams) WithTimeout(timeout time.Duration) *GetUsersOuIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get users ou ID params
func (o *GetUsersOuIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get users ou ID params
func (o *GetUsersOuIDParams) WithContext(ctx context.Context) *GetUsersOuIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get users ou ID params
func (o *GetUsersOuIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get users ou ID params
func (o *GetUsersOuIDParams) WithHTTPClient(client *http.Client) *GetUsersOuIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get users ou ID params
func (o *GetUsersOuIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get users ou ID params
func (o *GetUsersOuIDParams) WithID(id string) *GetUsersOuIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get users ou ID params
func (o *GetUsersOuIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersOuIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
