// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/Donders-Institute/dr-gateway/pkg/swagger/client/models"
)

// GetCollectionsReader is a Reader for the GetCollections structure.
type GetCollectionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCollectionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCollectionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetCollectionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCollectionsOK creates a GetCollectionsOK with default headers values
func NewGetCollectionsOK() *GetCollectionsOK {
	return &GetCollectionsOK{}
}

/*
GetCollectionsOK describes a response with status code 200, with default header values.

success
*/
type GetCollectionsOK struct {
	Payload *models.ResponseBodyCollections
}

// IsSuccess returns true when this get collections o k response has a 2xx status code
func (o *GetCollectionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get collections o k response has a 3xx status code
func (o *GetCollectionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get collections o k response has a 4xx status code
func (o *GetCollectionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get collections o k response has a 5xx status code
func (o *GetCollectionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get collections o k response a status code equal to that given
func (o *GetCollectionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get collections o k response
func (o *GetCollectionsOK) Code() int {
	return 200
}

func (o *GetCollectionsOK) Error() string {
	return fmt.Sprintf("[GET /collections][%d] getCollectionsOK  %+v", 200, o.Payload)
}

func (o *GetCollectionsOK) String() string {
	return fmt.Sprintf("[GET /collections][%d] getCollectionsOK  %+v", 200, o.Payload)
}

func (o *GetCollectionsOK) GetPayload() *models.ResponseBodyCollections {
	return o.Payload
}

func (o *GetCollectionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBodyCollections)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCollectionsInternalServerError creates a GetCollectionsInternalServerError with default headers values
func NewGetCollectionsInternalServerError() *GetCollectionsInternalServerError {
	return &GetCollectionsInternalServerError{}
}

/*
GetCollectionsInternalServerError describes a response with status code 500, with default header values.

failure
*/
type GetCollectionsInternalServerError struct {
	Payload *models.ResponseBody500
}

// IsSuccess returns true when this get collections internal server error response has a 2xx status code
func (o *GetCollectionsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get collections internal server error response has a 3xx status code
func (o *GetCollectionsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get collections internal server error response has a 4xx status code
func (o *GetCollectionsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get collections internal server error response has a 5xx status code
func (o *GetCollectionsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get collections internal server error response a status code equal to that given
func (o *GetCollectionsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get collections internal server error response
func (o *GetCollectionsInternalServerError) Code() int {
	return 500
}

func (o *GetCollectionsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /collections][%d] getCollectionsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCollectionsInternalServerError) String() string {
	return fmt.Sprintf("[GET /collections][%d] getCollectionsInternalServerError  %+v", 500, o.Payload)
}

func (o *GetCollectionsInternalServerError) GetPayload() *models.ResponseBody500 {
	return o.Payload
}

func (o *GetCollectionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ResponseBody500)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
