// Code generated by go-swagger; DO NOT EDIT.

// Package restapi dr-gateway
//
//	dr gateway APIs
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /v1
//	Version: 0.1.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
