// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCollectionsOuIDHandlerFunc turns a function with the right signature into a get collections ou ID handler
type GetCollectionsOuIDHandlerFunc func(GetCollectionsOuIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCollectionsOuIDHandlerFunc) Handle(params GetCollectionsOuIDParams) middleware.Responder {
	return fn(params)
}

// GetCollectionsOuIDHandler interface for that can handle valid get collections ou ID params
type GetCollectionsOuIDHandler interface {
	Handle(GetCollectionsOuIDParams) middleware.Responder
}

// NewGetCollectionsOuID creates a new http.Handler for the get collections ou ID operation
func NewGetCollectionsOuID(ctx *middleware.Context, handler GetCollectionsOuIDHandler) *GetCollectionsOuID {
	return &GetCollectionsOuID{Context: ctx, Handler: handler}
}

/*
	GetCollectionsOuID swagger:route GET /collections/ou/{id} getCollectionsOuId

get metadata of collections belonging to the organisational unit
*/
type GetCollectionsOuID struct {
	Context *middleware.Context
	Handler GetCollectionsOuIDHandler
}

func (o *GetCollectionsOuID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCollectionsOuIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
