// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCollectionsProjectIDHandlerFunc turns a function with the right signature into a get collections project ID handler
type GetCollectionsProjectIDHandlerFunc func(GetCollectionsProjectIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCollectionsProjectIDHandlerFunc) Handle(params GetCollectionsProjectIDParams) middleware.Responder {
	return fn(params)
}

// GetCollectionsProjectIDHandler interface for that can handle valid get collections project ID params
type GetCollectionsProjectIDHandler interface {
	Handle(GetCollectionsProjectIDParams) middleware.Responder
}

// NewGetCollectionsProjectID creates a new http.Handler for the get collections project ID operation
func NewGetCollectionsProjectID(ctx *middleware.Context, handler GetCollectionsProjectIDHandler) *GetCollectionsProjectID {
	return &GetCollectionsProjectID{Context: ctx, Handler: handler}
}

/*
	GetCollectionsProjectID swagger:route GET /collections/project/{id} getCollectionsProjectId

get metadata of collections associated with the project id
*/
type GetCollectionsProjectID struct {
	Context *middleware.Context
	Handler GetCollectionsProjectIDHandler
}

func (o *GetCollectionsProjectID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCollectionsProjectIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
