// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dccn-tg/dr-gateway/pkg/swagger/server/models"
)

// GetCollectionsProjectIDOKCode is the HTTP code returned for type GetCollectionsProjectIDOK
const GetCollectionsProjectIDOKCode int = 200

/*
GetCollectionsProjectIDOK success

swagger:response getCollectionsProjectIdOK
*/
type GetCollectionsProjectIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyCollections `json:"body,omitempty"`
}

// NewGetCollectionsProjectIDOK creates GetCollectionsProjectIDOK with default headers values
func NewGetCollectionsProjectIDOK() *GetCollectionsProjectIDOK {

	return &GetCollectionsProjectIDOK{}
}

// WithPayload adds the payload to the get collections project Id o k response
func (o *GetCollectionsProjectIDOK) WithPayload(payload *models.ResponseBodyCollections) *GetCollectionsProjectIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get collections project Id o k response
func (o *GetCollectionsProjectIDOK) SetPayload(payload *models.ResponseBodyCollections) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCollectionsProjectIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCollectionsProjectIDInternalServerErrorCode is the HTTP code returned for type GetCollectionsProjectIDInternalServerError
const GetCollectionsProjectIDInternalServerErrorCode int = 500

/*
GetCollectionsProjectIDInternalServerError failure

swagger:response getCollectionsProjectIdInternalServerError
*/
type GetCollectionsProjectIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewGetCollectionsProjectIDInternalServerError creates GetCollectionsProjectIDInternalServerError with default headers values
func NewGetCollectionsProjectIDInternalServerError() *GetCollectionsProjectIDInternalServerError {

	return &GetCollectionsProjectIDInternalServerError{}
}

// WithPayload adds the payload to the get collections project Id internal server error response
func (o *GetCollectionsProjectIDInternalServerError) WithPayload(payload *models.ResponseBody500) *GetCollectionsProjectIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get collections project Id internal server error response
func (o *GetCollectionsProjectIDInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCollectionsProjectIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
