// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Donders-Institute/dr-gateway/pkg/swagger/server/models"
)

// GetUsersOuIDOKCode is the HTTP code returned for type GetUsersOuIDOK
const GetUsersOuIDOKCode int = 200

/*
GetUsersOuIDOK success

swagger:response getUsersOuIdOK
*/
type GetUsersOuIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyUsers `json:"body,omitempty"`
}

// NewGetUsersOuIDOK creates GetUsersOuIDOK with default headers values
func NewGetUsersOuIDOK() *GetUsersOuIDOK {

	return &GetUsersOuIDOK{}
}

// WithPayload adds the payload to the get users ou Id o k response
func (o *GetUsersOuIDOK) WithPayload(payload *models.ResponseBodyUsers) *GetUsersOuIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users ou Id o k response
func (o *GetUsersOuIDOK) SetPayload(payload *models.ResponseBodyUsers) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersOuIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetUsersOuIDInternalServerErrorCode is the HTTP code returned for type GetUsersOuIDInternalServerError
const GetUsersOuIDInternalServerErrorCode int = 500

/*
GetUsersOuIDInternalServerError failure

swagger:response getUsersOuIdInternalServerError
*/
type GetUsersOuIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewGetUsersOuIDInternalServerError creates GetUsersOuIDInternalServerError with default headers values
func NewGetUsersOuIDInternalServerError() *GetUsersOuIDInternalServerError {

	return &GetUsersOuIDInternalServerError{}
}

// WithPayload adds the payload to the get users ou Id internal server error response
func (o *GetUsersOuIDInternalServerError) WithPayload(payload *models.ResponseBody500) *GetUsersOuIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get users ou Id internal server error response
func (o *GetUsersOuIDInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetUsersOuIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
