// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Donders-Institute/dr-gateway/pkg/swagger/server/models"
)

// GetCollectionsOKCode is the HTTP code returned for type GetCollectionsOK
const GetCollectionsOKCode int = 200

/*
GetCollectionsOK success

swagger:response getCollectionsOK
*/
type GetCollectionsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBodyCollections `json:"body,omitempty"`
}

// NewGetCollectionsOK creates GetCollectionsOK with default headers values
func NewGetCollectionsOK() *GetCollectionsOK {

	return &GetCollectionsOK{}
}

// WithPayload adds the payload to the get collections o k response
func (o *GetCollectionsOK) WithPayload(payload *models.ResponseBodyCollections) *GetCollectionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get collections o k response
func (o *GetCollectionsOK) SetPayload(payload *models.ResponseBodyCollections) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCollectionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCollectionsInternalServerErrorCode is the HTTP code returned for type GetCollectionsInternalServerError
const GetCollectionsInternalServerErrorCode int = 500

/*
GetCollectionsInternalServerError failure

swagger:response getCollectionsInternalServerError
*/
type GetCollectionsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseBody500 `json:"body,omitempty"`
}

// NewGetCollectionsInternalServerError creates GetCollectionsInternalServerError with default headers values
func NewGetCollectionsInternalServerError() *GetCollectionsInternalServerError {

	return &GetCollectionsInternalServerError{}
}

// WithPayload adds the payload to the get collections internal server error response
func (o *GetCollectionsInternalServerError) WithPayload(payload *models.ResponseBody500) *GetCollectionsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get collections internal server error response
func (o *GetCollectionsInternalServerError) SetPayload(payload *models.ResponseBody500) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCollectionsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
