apiKey: demo
auth:
  demo: demo123
jwksEndpoint: https://auth-dev.dccn.nl/.well-known/openid-configuration/jwks
dr:
  irodsHost: icat.localhost
  irodsPort: 1247
  irodsZone: nl.ru.donders
  irodsUser: user
  irodsPass: pass
  irodsAuthScheme: native
  irodsSslCacert: /opt/irods/ssl/icat-prod.pem
  irodsSslKeysize: 32
  irodsSslAlgorithm: AES-256-CBC
  irodsSslSaltSize: 8
  irodsHashRounds: 16
  organisationalUnits:
    - DCCN
    - DCC
    - DCN
    - DCMN